# Generated by Django 2.2 on 2019-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0003_auto_20190516_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasesCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя состояния с правилами')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние с фразами',
                'verbose_name_plural': 'Состояния с фразами',
            },
        ),
    ]
