# Generated by Django 2.2 on 2019-06-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0005_phraseblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhraseBlock',
        ),
        migrations.DeleteModel(
            name='PhrasesCondition',
        ),
    ]
