# Generated by Django 2.2 on 2019-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0001_initial'),
        ('dictapp', '0006_auto_20190601_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictwithrules',
            name='use_in_block',
            field=models.ManyToManyField(to='phrase_cond_app.PhraseBlock'),
        ),
    ]
