# Generated by Django 2.2 on 2019-06-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0007_dictwithrules_use_in_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictwithrules',
            name='use_in_block',
        ),
    ]
