# Generated by Django 2.2 on 2019-06-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasesCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя состояния с правилами')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние с фразами',
                'verbose_name_plural': 'Состояния с фразами',
            },
        ),
        migrations.CreateModel(
            name='PhraseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_phrase', models.CharField(max_length=255, verbose_name='Базовая фраза')),
                ('phrase_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_condition', to='phrase_cond_app.PhrasesCondition', verbose_name='')),
            ],
            options={
                'verbose_name': 'Блок с фразами',
                'verbose_name_plural': 'Блоки с фразами',
            },
        ),
    ]
