# Generated by Django 2.2 on 2019-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0008_remove_dictwithrules_use_in_block'),
        ('phrase_cond_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraseblock',
            name='phrases_parts',
            field=models.ManyToManyField(to='dictapp.DictWithRules'),
        ),
    ]
