# Generated by Django 2.2 on 2019-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0004_remove_phraseblock_phrases_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraseblock',
            name='phrases_parts',
            field=models.TextField(blank=True, verbose_name='Основные правила'),
        ),
    ]
