# Generated by Django 2.2 on 2019-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0006_auto_20190601_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseblock',
            name='phrases_parts',
            field=models.ManyToManyField(related_name='phrase_condition', to='dictapp.DictWithRules'),
        ),
    ]
