# Generated by Django 2.2 on 2019-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0007_auto_20190602_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseblock',
            name='phrases_parts',
            field=models.ManyToManyField(related_name='phrases_parts', to='dictapp.DictWithRules'),
        ),
    ]
