# Generated by Django 2.2 on 2019-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0008_remove_dictwithrules_use_in_block'),
        ('phrase_cond_app', '0009_phraseblock_phrases_parts_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraseblock',
            name='next_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='phraseblock',
            name='phrases_exact',
            field=models.ManyToManyField(related_name='phrases_exact', to='dictapp.DictWithRules'),
        ),
    ]
