# Generated by Django 2.2 on 2019-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0010_auto_20190609_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseblock',
            name='phrases_exact',
            field=models.ManyToManyField(null=True, related_name='phrases_exact', to='dictapp.DictWithRules'),
        ),
    ]
