# Generated by Django 2.2 on 2019-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_cond_app', '0011_auto_20190610_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseblock',
            name='phrases_exact',
            field=models.ManyToManyField(blank=True, null=True, related_name='phrases_exact', to='dictapp.DictWithRules'),
        ),
    ]
